---
- debug:
    var: "{{ item }}"
  with_items:
    - tower_host
    - tower_username
    - tower_password
    - tower_inventory
    - tower_inventory_description
    - tower_org
    - tower_inventory_config

- name: Add Tower inventory
  tower_inventory:
    name: "{{ tower_inventory }}"
    description: "{{ tower_inventory_description }}"
    organization: "{{ tower_org }}"
    state: present
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Configure Tower Inventory
  tower_inventory:
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    name: "{{ tower_inventory }}"
    description: "{{ tower_inventory_description }}"
    organization: "{{ tower_org }}"
    variables:
      - student_id: "{{ student_id }}"
      - lab_user: "{{ lab_user }}"

- include: inventory/groups.yml
  when: tower_inventory_group_config|bool == true
...
