---
- name: Add Tower Cloud Credential
  tower_credential:
    name: "{{ tower_credential_cloud }}"
    description: "{{ tower_credential_cloud_description }}"
    kind: "{{ tower_credential_cloud_kind }}"
    organization: "{{ tower_org }}"
    state: present
    username: "{{ tower_credential_cloud_username }}"
    password: "{{ tower_credential_cloud_password }}"
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
...
