---
- name: Stage {{ tower_credential_machine }} Private Key
  synchronize:
    src: "{{ tower_credential_machine_ssh_key_data }}"
    dest: "/tmp/{{ tower_credential_machine_ssh_key_data }}"

- name: Add Tower Machine Credential
  tower_credential:
    name: "{{ tower_credential_machine }}"
    description: "{{ tower_credential_machine_description }}"
    kind: "{{ tower_credential_machine_kind }}"
    organization: "{{ tower_org }}"
    state: present
    ssh_key_data: "/tmp/{{ tower_credential_machine_ssh_key_data }}"
    username: "{{ tower_credential_machine_username }}"
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"

- name: Remove {{ tower_credential_machine }} staging file
  file:
    path: "/tmp/{{ tower_credential_machine_ssh_key_data }}"
    state: absent
...
