---
- hosts: masters
  vars:
    templates_query: '{range .items[*]}{.metadata.name}{"\n"}{end}'
    image_streams_query: '{range .items[*]}{.metadata.name}{"\n"}{end}'
    templates_to_keep: ['cakephp-mysql-persistent', 'metrics-deployer-template', 'registry-console']
    image_streams_to_keep: ['php', 'mysql']
    service_catalog_projects_to_annotate: ['kube-service-catalog']
    default_node_selector: 'type=app'
    service_catalog_default_node_selector: 'openshift-infra=apiserver'
    cfme_template: https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.6/roles/openshift_examples/files/examples/v3.6/cfme-templates/cfme-template.yaml
  tasks:
  - name: Get templates
    command: >
      oc get templates -n openshift -o jsonpath='{{ templates_query }}'
    register: templates

  - name: Remove templates
    command: >
      oc delete templates -n openshift {{ item }}
    when: item not in templates_to_keep
    with_items:
    - "{{ templates.stdout_lines }}"

  - name: Get ImageStreams
    command: >
      oc get is -n openshift -o jsonpath='{{ image_streams_query }}'
    register: image_streams

  - name: Remove ImageStreams
    command: >
      oc delete is -n openshift {{ item }}
    when: item not in image_streams_to_keep
    with_items:
      - "{{ image_streams.stdout_lines }}"

  - name: Delete image stream tags not needed
    command: >
      oc tag {{ item }} -d
    register: tag_delete
    failed_when: tag_delete.rc != 0 and 'not found' not in tag_delete.stderr
    changed_when: tag_delete.rc == 0
    with_items:
    - openshift/php:5.5
    - openshift/php:5.6
    - openshift/mysql:5.5
    - openshift/mysql:5.6

  - name: Setup CFME Template
    command: >
      oc apply -n openshift -f {{ cfme_template }}
  
  - name: Annotate Service Catalog Projects
    command: >
      oc annotate namespace {{ item }} openshift.io/node-selector='{{ service_catalog_default_node_selector }}' --overwrite
    with_items: "{{ service_catalog_projects_to_annotate }}"

  - name: Set Default Node Selector
    become: true
    lineinfile: dest=/etc/origin/master/master-config.yaml  state=present regexp="defaultNodeSelector" line='  defaultNodeSelector{{ ':' }} {{ default_node_selector }}'

  - name: Locate OpenShift API Server
    command: >
      oc whoami --show-server=true
    register: whoami_result
  
  - name: Restart OpenShift Master
    become: true
    systemd:
      name: atomic-openshift-master
      state: restarted
    when: "groups['masters'] | length  == 1"

  - name: Restart OpenShift Master API
    become: true
    systemd:
      name: atomic-openshift-master-api
      state: restarted
    when: "groups['masters'] | length > 1"

  - name: Verify API Server
    become: true
    command: >
      curl --silent
      --cacert /etc/origin/master/ca-bundle.crt
      {{ whoami_result.stdout }}/healthz/ready
    args:
      warn: no
    register: l_api_available_output
    until: l_api_available_output.stdout == 'ok'
    retries: 120
    delay: 1
    changed_when: false

  - name: Delete Service Catalog Pods
    command: >
      oc delete pods --all -n {{ item}}
    with_items: "{{ service_catalog_projects_to_annotate }}"
