---
- name: Unconfigure Tower
  hosts: tower_instances
  gather_facts: no
  vars:
    ansible_ssh_user: ec2-user
    ansible_python_interpreter: "python"
  vars_files:
    - aws_vars.yml
    - tower_vars.yml

    - name: Set Tower CLI Host
      command: tower-cli config host "{{ hostvars[inventory_hostname].public_ip }}"
    - name: Set Tower CLI Username
      command: tower-cli config username "{{ tower_username }}"
    - name: Set Tower CLI Password
      command: tower-cli config password "{{ tower_password }}"

    - name: Remove Demo Job Template
      tower_job_template:
        name: "Demo Job Template"
        state: absent
        project: "Demo Project"
        playbook: ""
        job_type: run
        tower_host: "{{ hostvars[inventory_hostname].public_ip }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
    
    - name: Remove Demo Project
      tower_project:
        name: "Demo Project"
        organization: "{{ tower_org }}"
        state: absent
        tower_host: "{{ hostvars[inventory_hostname].public_ip }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"

    - name: Remove Demo Inventory
      tower_inventory:
        tower_host: "{{ hostvars[inventory_hostname].public_ip }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        name: "Demo Inventory"
        organization: "{{ tower_org }}"
        state: absent
